name: ziggurat_simple_maps
version: 0.1.0
description: Provides simple maps for use with [Ziggurat](https://pub.dev/packages/ziggurat).
repository: https://github.com/chrisnorman7/ziggurat_simple_maps
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dart_sdl: ^0.10.1
  ziggurat: ^0.54.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
