name: ziggurat_simple_maps
version: 0.0.0
description: Provides simple maps for use with [Ziggurat](https://pub.dev/packages/ziggurat).
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
